CREATE TABLE IF NOT EXISTS artists (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	commonName TEXT UNIQUE,
	aliases TEXT
);

CREATE TABLE IF NOT EXISTS images (
	hash TEXT PRIMARY KEY,
	imageKey TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS drawings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	hash TEXT NOT NULL,
	artistId INTEGER NOT NULL,
	FOREIGN KEY (hash) REFERENCES images(hash) ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY (artistId) REFERENCES artists(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS history (
    day INTEGER PRIMARY KEY UNIQUE,
    time INTEGER UNIQUE,
	drawingId INTEGER
);
