CREATE TABLE IF NOT EXISTS artists (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	commonName TEXT UNIQUE,
	aliases TEXT
);

CREATE TABLE IF NOT EXISTS drawings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	image TEXT,
	artistId INTEGER NOT NULL,
	FOREIGN KEY (artistId) REFERENCES artists(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS history (
    day INTEGER PRIMARY KEY UNIQUE,
    time INTEGER UNIQUE,
	drawingId INTEGER
);
